export { Api } from './api/api';
export { Items } from '../mocks/providers/items';
export { Settings } from './settings/settings';
export { User } from './user/user';
export { Global } from './global/global';
export { AlunoProvider } from '../mocks/providers/aluno';
export { DisciplinaProvider } from '../mocks/providers/disciplina';
export { MatriculaProvider } from '../mocks/providers/matricula';
export { TurmaProvider } from '../mocks/providers/turma';